# Generated by Django 6.0.1 on 2026-01-29 06:56

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='images/')),
                ('audio', models.FileField(storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='audios/')),
                ('video', models.FileField(storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='videos/')),
                ('resume', models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='files/')),
            ],
        ),
    ]
