# Generated by Django 6.0.1 on 2026-01-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='employee_profile/')),
                ('password', models.CharField(default='N/A', max_length=100)),
                ('department', models.CharField(max_length=50, null=True)),
                ('d_code', models.CharField(max_length=20, null=True)),
                ('d_des', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(blank=True, max_length=15, null=True)),
                ('qualification', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('video', models.FileField(blank=True, null=True, upload_to='video/')),
                ('document', models.FileField(blank=True, null=True, upload_to='document/')),
                ('password', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('query', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=50)),
                ('status', models.CharField(default='panding', max_length=10)),
                ('solution', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
