# Generated by Django 6.0.1 on 2026-01-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
