# Generated by Django 6.0.1 on 2026-01-16 07:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_query_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addemployee',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
