# Generated by Django 6.0.1 on 2026-01-17 06:48

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_addemployee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addemployee',
            name='contact',
            field=models.CharField(max_length=15, validators=[app.models.Emp1_contact]),
        ),
    ]
