# Generated by Django 6.0.1 on 2026-01-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhar',
            name='adhar_no',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
