# Generated by Django 6.0.1 on 2026-01-19 06:18

import app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, validators=[app.models.validate_name])),
                ('name', models.CharField(max_length=50, validators=[app.models.validate_name])),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('mobile', models.CharField(max_length=10, unique=True, validators=[app.models.validate_mobile])),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18)])),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=50, validators=[app.models.validate_password])),
                ('confirm_password', models.CharField(max_length=50)),
            ],
        ),
    ]
