# Generated by Django 6.0.1 on 2026-01-20 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_aadhar_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='mobile',
            new_name='contact',
        ),
    ]
