# Generated by Django 6.0.1 on 2026-01-21 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_mobile_student_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhar',
            name='adhar_no',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='xyz',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.aadhar'),
        ),
    ]
