# Generated by Django 6.0.1 on 2026-01-21 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_aadhar_adhar_no_alter_student_xyz'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aadhar',
            new_name='Aadhaar',
        ),
        migrations.RenameField(
            model_name='aadhaar',
            old_name='adhar_no',
            new_name='aadhaar_no',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='xyz',
            new_name='aadhaar',
        ),
    ]
