# Generated by Django 6.0.1 on 2026-01-21 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_aadhar_aadhaar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aadhaar',
            old_name='create_by',
            new_name='created_by',
        ),
    ]
